services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
    networks:
      - database
    depends_on:
      - database
    ports:
      - 3000:3000

  database:
    image: postgres:alpine
    container_name: database
    environment:
      POSTGRES_DB: ${DB}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - database

networks:
  database:
    driver: bridge

volumes:
  database:
